### PR TITLE
feat: Add updated issue and PR templates

### PR DESCRIPTION
**Pull request by leocencetti**
Update issue templates to use forms

These templates are inspired to the ones present in https://github.com/fbx-org/PX4-Autopilot.
You can try them here:
 - [Bug Report](https://github.com/leocencetti/fbx_github/blob/feat-updated-issue-templates/.github/ISSUE_TEMPLATE/01_bug_report.yml)
 - [Feature Request](https://github.com/leocencetti/fbx_github/blob/feat-updated-issue-templates/.github/ISSUE_TEMPLATE/01_feature_request.yml)

### CODE REVIEW

**Review by agogna — CHANGES_REQUESTED** [review]
@dlauener @jlecoeur, let's plan a small meeting to discuss this PR and Asio Change and Defect management.

**Review by jlecoeur — DISMISSED** [review]
Looks good to me.

Keep in mind that this repo is public because of a GitHub limitation.

**Comment by jlecoeur** [comment]
> @dlauener @jlecoeur, let's plan a small meeting to discuss this PR and Asio Change and Defect management.

Sure.

**Comment by dlauener** [comment]
@agogna @jlecoeur @leocencetti 
It looks good, but it may be too drone-centric at the moment.
image

We could make something more generic, or the opposite and create two "bug" categories  [bug - drone] / [bug - soft]
For "Connect", we may need the environment, region, tenant (customer), a datetime when it occurred, etc...

**Comment by leocencetti** [comment]
As decided, these templates are now generic:
 - [Bug Report](https://github.com/leocencetti/fbx_github/blob/feat-updated-issue-templates/.github/ISSUE_TEMPLATE/01_bug_report.yml)
 - [Feature Request](https://github.com/leocencetti/fbx_github/blob/feat-updated-issue-templates/.github/ISSUE_TEMPLATE/01_feature_request.yml)

**Review by jlecoeur — APPROVED** [review]

**Review by agogna — APPROVED** [review]

**Comment by leocencetti** [comment]
@jlecoeur @agogna please 
merge

**Pull request merged**
